// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// lovable-mcp-supabase-entry.ts
import mcp from "npm:C:\\Users\\jayde\\AppData\\Local\\Temp\\claude\\c--Users-jayde-senseglow-system\\1a4f6d47-d92c-48e7-a075-ad818bef735b\\scratchpad\\sgrepo\\src\\lib\\mcp\\index.ts";
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp, { functionName: "mcp" }));
