// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/shopify-client.ts
var SHOPIFY_API_VERSION = "2025-07";
var SHOPIFY_STORE_DOMAIN = "senseglow-smart-light-5jjoq.myshopify.com";
var SHOPIFY_STOREFRONT_URL = `https://${SHOPIFY_STORE_DOMAIN}/api/${SHOPIFY_API_VERSION}/graphql.json`;
var SHOPIFY_STOREFRONT_TOKEN = "d888e2f5ee17de858e6626f4c34cf9b7";
var ENABLED_PRODUCT_HANDLES = [
  "senseglow_ambient_motion_bar",
  "senseglow_wave",
  "senseglow_flex",
  "senseglow_solar_lantern",
  "senseglow_wall_lamp"
];
async function storefront(query, variables = {}) {
  const res = await fetch(SHOPIFY_STOREFRONT_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      "X-Shopify-Storefront-Access-Token": SHOPIFY_STOREFRONT_TOKEN,
      Accept: "application/json"
    },
    body: JSON.stringify({ query, variables })
  });
  if (!res.ok) throw new Error(`Shopify Storefront error ${res.status}`);
  const json = await res.json();
  if (json.errors) throw new Error(json.errors.map((e) => e.message).join("; "));
  return json.data;
}
var PRODUCT_LIST_QUERY = `
  query ListProducts($first: Int!, $query: String) {
    products(first: $first, query: $query) {
      edges {
        node {
          id
          title
          handle
          description
          priceRange { minVariantPrice { amount currencyCode } maxVariantPrice { amount currencyCode } }
          images(first: 1) { edges { node { url altText } } }
        }
      }
    }
  }
`;
var PRODUCT_DETAIL_QUERY = `
  query GetProduct($handle: String!) {
    productByHandle(handle: $handle) {
      id
      title
      handle
      description
      descriptionHtml
      productType
      tags
      priceRange { minVariantPrice { amount currencyCode } maxVariantPrice { amount currencyCode } }
      images(first: 20) { edges { node { url altText } } }
      options { name values }
      variants(first: 100) {
        edges {
          node {
            id
            title
            availableForSale
            price { amount currencyCode }
            selectedOptions { name value }
          }
        }
      }
    }
  }
`;
function productUrl(handle) {
  return `https://senseglow.shop/product/${handle}`;
}
async function listEnabledProducts() {
  const data = await storefront(PRODUCT_LIST_QUERY, {
    first: 50
  });
  return data.products.edges.map(({ node }) => node).filter((n) => ENABLED_PRODUCT_HANDLES.includes(n.handle)).map((n) => ({
    title: n.title,
    handle: n.handle,
    url: productUrl(n.handle),
    description: n.description,
    price: {
      min: n.priceRange.minVariantPrice.amount,
      max: n.priceRange.maxVariantPrice.amount,
      currency: n.priceRange.minVariantPrice.currencyCode
    },
    image: n.images.edges[0]?.node?.url ?? null
  }));
}
async function searchProducts(query, limit) {
  const data = await storefront(PRODUCT_LIST_QUERY, {
    first: Math.min(Math.max(limit, 1), 20),
    query
  });
  return data.products.edges.map(({ node }) => node).filter((n) => ENABLED_PRODUCT_HANDLES.includes(n.handle)).map((n) => ({
    title: n.title,
    handle: n.handle,
    url: productUrl(n.handle),
    description: n.description,
    price: {
      min: n.priceRange.minVariantPrice.amount,
      max: n.priceRange.maxVariantPrice.amount,
      currency: n.priceRange.minVariantPrice.currencyCode
    },
    image: n.images.edges[0]?.node?.url ?? null
  }));
}
async function getProductByHandle(handle) {
  const data = await storefront(PRODUCT_DETAIL_QUERY, { handle });
  const n = data.productByHandle;
  if (!n) return null;
  return {
    title: n.title,
    handle: n.handle,
    url: productUrl(n.handle),
    description: n.description,
    productType: n.productType,
    tags: n.tags,
    price: {
      min: n.priceRange.minVariantPrice.amount,
      max: n.priceRange.maxVariantPrice.amount,
      currency: n.priceRange.minVariantPrice.currencyCode
    },
    image: n.images.edges[0]?.node?.url ?? null,
    images: n.images.edges.map((e) => ({ url: e.node.url, alt: e.node.altText })),
    options: n.options,
    variants: n.variants.edges.map((e) => ({
      id: e.node.id,
      title: e.node.title,
      availableForSale: e.node.availableForSale,
      price: { amount: e.node.price.amount, currency: e.node.price.currencyCode },
      options: e.node.selectedOptions
    }))
  };
}

// src/lib/mcp/tools/list-products.ts
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List all SenseGlow products currently sold on senseglow.shop, with price range, description, and product page URL.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async () => {
    const products = await listEnabledProducts();
    return {
      content: [{ type: "text", text: JSON.stringify(products, null, 2) }],
      structuredContent: { products }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Get full details for a single SenseGlow product by its handle (e.g. 'senseglow_wave'): description, images, variants (color/size), prices, availability, and product page URL.",
  inputSchema: {
    handle: z.string().min(1).describe("The product handle, e.g. 'senseglow_wave' or 'senseglow_ambient_motion_bar'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ handle }) => {
    const product = await getProductByHandle(handle);
    if (!product) {
      return {
        content: [{ type: "text", text: `No product found with handle '${handle}'.` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(product, null, 2) }],
      structuredContent: { product }
    };
  }
});

// src/lib/mcp/tools/search-products.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var search_products_default = defineTool3({
  name: "search_products",
  title: "Search products",
  description: "Search SenseGlow products by keyword (matches title, description, tags). Returns summaries with prices and product page URLs.",
  inputSchema: {
    query: z2.string().min(1).describe("Search keywords, e.g. 'wave', 'solar lantern', 'motion sensor'."),
    limit: z2.number().int().min(1).max(20).default(10).describe("Maximum results to return (1-20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, limit }) => {
    const products = await searchProducts(query, limit);
    return {
      content: [{ type: "text", text: JSON.stringify(products, null, 2) }],
      structuredContent: { products }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "bepcnohdxsoxhdjlviqu";
var mcp_default = defineMcp({
  name: "senseglow-mcp",
  title: "SenseGlow Shop",
  version: "0.2.0",
  instructions: "Read-only access to SenseGlow's public product catalog (senseglow.shop). Sign in with your SenseGlow account. Use `list_products` to see all products, `search_products` to find products by keyword, and `get_product` to fetch full details (variants, images, prices) for a specific product by its handle.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_products_default, get_product_default, search_products_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
